### ISSUE TITLE
Documentation out of sync

### ISSUE THREAD

**Issue by richardsimko** [charliedowler/soy-to-require#3]
Currently the docs seem to be out of sync with what's in the NPM repo. In addition the version in the NPM repo hasn't been updated in the last 12 months and a lot of changes seem to have been made since then. Would it be possible to get an update to the repo or is the recommended approach to just grab the code?

**Comment by charliedowler** [comment]
Hey,

Sorry for the delay, I've just published the latest version.

https://www.npmjs.com/package/soy-to-require

Cheers,
Charlie
